2024-08-27 update : prep for inf. wout dist.
CDCgov/ww-inference-model pull request #104
Opened 2024-08-27 14:12 UTC by cbernalz

Regarding https://github.com/CDCgov/ww-inference-model/issues/96#issue-2487415321 .

2024-08-28 17:41 UTC, dylanhmorris requested changes
A couple comments on the Stan side of things @cbernalz

2024-08-28 17:41 UTC, dylanhmorris commented on inst/stan/wwinference.stan
> +  cholesky_factor_corr[n_subpops-1] L_Omega;
This should be defined only if we're in the "inferred correlation but no distance matrix case". The way to do that in stan is to make it size zero in other cases.

See https://discourse.mc-stan.org/t/if-else-statement-inside-parameter-block/13937/2 for details

2024-08-28 17:41 UTC, dylanhmorris commented on inst/stan/wwinference.stan
> +    L_Omega ~ lkj_corr_cholesky(2.0);
Related to the above, wrap this in an `if`

2024-08-28 21:50 UTC, dylanhmorris reviewed
Reflecting on this I think instead of two boolean flags (`ind_corr_func` and `exp_cor_func`) I'd just have a single integer `coff_func`, variable (`lower=0, upper=2>` where `0=ind, 1=lkj, 2=exp`, etc. This will also make it easier to extend in the future.

And then in the R function I'd have a string argument named "site_correlation_model" with choices `"iid"`,`lkj`, and `exponential`, or similar names (default `iid`)

2024-08-28 21:50 UTC, dylanhmorris commented on R/get_stan_data.R
> +      exp_corr_func <- 1
```suggestion
      exp_corr_func <- 1L
```

2024-08-28 21:50 UTC, dylanhmorris commented on R/get_stan_data.R
> +      exp_corr_func <- 0
```suggestion
      exp_corr_func <- 0L
```

2024-08-28 21:50 UTC, dylanhmorris commented on R/get_stan_data.R
> +    exp_corr_func <- 0
```suggestion
    exp_corr_func <- 0L
```

2024-08-29 17:30 UTC, kaitejohnson reviewed
This looks really good to me, nice job implementing this, it looks really clean!

2024-08-29 17:41 UTC, cbernalz commented on R/get_stan_data.R
> +    exp_corr_func = exp_corr_func
@kaitejohnson I was just implementing what @dylanhmorris suggested.  I am having the string in `get_stan_data.R` where it is "iid" then ind_corr_func is set to 1 / exp_corr_func is set to 0 / ljk_corr_func is set to 0.  If the string is set to "exponential" then ind_corr_func is set to 0 / exp_corr_func is set to 1 / ljk_corr_func is set to 0.  If the string is set to "lkj" then ind_corr_func is set to 0 / exp_corr_func is set to 0 / ljk_corr_func is set to 1.  I just repushed @dylanhmorris's change request, can you take a look at it to see what we can do with this idea?

2024-08-29 18:06 UTC, dylanhmorris submitted a review, later dismissed
LGTM

2024-08-29 18:06 UTC, dylanhmorris commented on R/get_stan_data.R
> +         * must be either iid, exponential, lkj*")
```suggestion
         * must be one of 'iid', 'exponential', 'lkj'*")
```

2024-08-29 18:06 UTC, dylanhmorris commented on inst/stan/wwinference.stan
> +    print("Model will not get to there, get_stan_data.R provides protections");
Still worth raising an error even if something should not be occur.
```suggestion
    reject("Unsupported choice of correlation function. Check the data passed to Stan");
```

2024-08-29 19:06 UTC, kaitejohnson requested changes
Just requested changes to the language a bit. otherwise this looks great!

2024-08-30 01:38 UTC, kaitejohnson approved these changes
This looks good to me, thanks for making that language change I think it is more clear!

2024-08-30 17:46 UTC, dylanhmorris requested changes
Very close, thanks @cbernalz! Just a few small typo fixes and edits to make error messages clearer. Let me know when ready for re-review

2024-08-30 17:46 UTC, dylanhmorris commented on R/get_stan_data.R
> +#' 1 for an exponential correlation structure based off distance matrix, and 3
```suggestion
#' 1 for an exponential correlation structure based off distance matrix, and 2
```

2024-08-30 17:46 UTC, dylanhmorris commented on R/get_stan_data.R
> +         * must be either 0-iid, 1-exponential, 2-lkj*")
```suggestion
    cli::cli_abort(c("Correlation structure requested currently not implemented.",
    Must be one of 0 (iid), 1 (exponential), and (2) lkj. Got {corr_structure_switch}"))
```

2024-08-30 17:46 UTC, dylanhmorris commented on R/wwinference.R
> +#' 1 for an exponential correlation structure based off distance matrix, and 3
```suggestion
#' 1 for an exponential correlation structure based off distance matrix, and 2
```

2024-08-30 17:46 UTC, dylanhmorris commented on inst/stan/wwinference.stan
> +    print("Model will not get to there, get_stan_data.R provides protections");
```suggestion
    reject("Model should not reach this point. Invalid corr_structure_switch value. Check model code");
```

2024-08-30 20:09 UTC, dylanhmorris approved these changes
LGTM

2024-08-30 23:10 UTC, merged