Add hex logo to repo
CDCgov/ww-inference-model pull request #148
Opened 2024-09-09 12:34 UTC by kaitejohnson

2024-09-09 17:20 UTC, seabbs commented
love to see it. make sure to you `usethis::use_logo()` and check with @dylanhmorris about CDC logo rules (I am just guessing there are some).

2024-09-09 19:23 UTC, kaitejohnson commented
Good idea, didn't realize that existed! Will check with Kayla and Isaac

2024-09-09 20:13 UTC, dylanhmorris commented
I'm afraid I don't know anything offhand about logo rules / policies (if any), but will investigate

2024-09-10 15:25 UTC, athowes commented
Can you add code to generate the hex plot? Incase you need to change it in future.

2024-09-10 17:39 UTC, kaitejohnson commented
> Can you add code to generate the hex plot? Incase you need to change it in future.

@athowes I didn't make it, Kayla English generated it in illustrator! I think it's ok for it not to be auto-updated.

2024-09-10 17:46 UTC, damonbayer commented
@kaitejohnson if it's generated in illustrator, can she provide an svg for us?

2024-09-12 02:27 UTC, kaitejohnson commented
Not loving the positioning now but can play modify the geometry or the title text.

2024-09-12 17:29 UTC, dylanhmorris commented
> Not loving the positioning now but can play modify the geometry or the title text.

I would check the dimensions of the `.svg`. Looks like there might be some blank space above and below the hex.

2024-09-12 21:20 UTC, gvegayon commented
I just saw this, @kaitejohnson. I LOVE IT! I think that once the CDC rules for this sort of stuff are clear, we are good to go!

2024-09-13 14:59 UTC, kaitejohnson commented
@gvegayon Thank Kayla English!!

2024-09-13 20:36 UTC, dylanhmorris commented
@kaitejohnson I think this needs the changes from `main` pulled in so that the required checks will run.

2024-09-13 20:58 UTC, dylanhmorris requested changes
Need to delete old logos

2024-09-13 20:58 UTC, dylanhmorris commented on man/figures/wwinference-logo.png
delete this?

2024-09-13 20:58 UTC, dylanhmorris commented on man/figures/wwinference-logo.svg
delete this also?

2024-09-13 22:14 UTC, dylanhmorris approved these changes
LGTM!

2024-09-14 00:25 UTC, merged