Issue 200: Modify plot methods
CDCgov/ww-inference-model pull request #218
Opened 2024-10-17 15:48 UTC by kaitejohnson

This PR closes #200. This makes a few minor changes:
- modifies plot of forecasted counts to not expect an evaluation dataset
- adds an example in the vignette to plot without the evaluation data
- replaces `scales = "free"` with `scales = "free_y"` so that the x-axis shared for the dates in the wastewater concentration plot. 

@gvegayon If you think there's a better way to handle the x axis dates (or that we should exclude them) lmk. I think best to have them as a default?

2024-10-17 17:49 UTC, dylanhmorris requested changes
Add a test and then this should be ready.

2024-10-17 17:49 UTC, dylanhmorris commented on NEWS.md
> +#wwinference dev
```suggestion
# wwinference dev
```

2024-10-17 17:49 UTC, dylanhmorris commented on R/figures.R
Would be good to add a test that this can work both both `NULL` and non-`NULL` `count_data_eval` arguments.

Something as simple as confirming that ggplot plots are created without error in both cases with a tiny toy dataset.

2024-10-18 21:39 UTC, gvegayon commented
I'm unsure about your question, @kaitejohnson, as I am no expert in ggplot2. All I can think is that I would (a) keep the detailing of the figures to a minimum or (b) ensure additional modifications are optional (e.g., `add_fancy_scales = TRUE`).

2024-10-18 22:07 UTC, kaitejohnson commented
Well it will default to plotting the dates so they all overlap and are unreadable, which is why I added the 45 degree angle dates... I think we should leave for now bc my understanding of ggplot is that the later thing takes precedent so the user can always override

2024-10-23 14:41 UTC, kaitejohnson commented
Need to add this to the change log (note to self)

2024-10-23 18:36 UTC, dylanhmorris approved these changes
LGTM, thanks @kaitejohnson

2024-10-23 18:36 UTC, merged