10 add hosp admissions only model functionality
CDCgov/ww-inference-model pull request #24
Opened 2024-07-15 16:01 UTC by kaitejohnson

This PR closes #10 and also has a bit of scope creep to fix the rendering of the vignette/some bugs in the figure generating function. Changes include:
- adding a component to the vignette that fits the model to only hospital admissions and plots the resulting hospital admissions forecasts
- adjusted the generate simulated data function and resulting package data to include a larger population size, bc the low counts of admissions were causing diagnostic issues
- modified `get_model_spec()` and `get_stan_data()` to take in `include_ww` as an argument, to specify whether or not to fit the model to wastewater data
- adjusted the way the figures were rendering in the vignette (mirroring [epinowcast vignette](https://github.com/epinowcast/epinowcast/blob/d957b21af07c7708d8ae28fc248fffe39d453828/vignettes/epinowcast.Rmd#L299C1-L302C7) to point to a figure folder which contains figures that render the width of the screen

2024-07-16 21:24 UTC, kaitejohnson commented
Note this doesn't do what I mentioned in the MSR community meeting today -- it doesn't add the functionality to not have wastewater data. I will do this in a separate issue... I think by making an empty dataset

2024-07-18 16:24 UTC, kaitejohnson commented
@dylanhmorris not a huge rush but this is ready for review and is relatively small (tweaks to vignette + the easy version of hospital admissions only functionality)

2024-07-18 16:26 UTC, kaitejohnson commented
Although I am realizing now that I set up the github branch protections to require status checks to pass, which includes deploy of `pkgdown` but I think deploy wouldn't happen until the PR gets merged to main so maybe I should remove that one

2024-07-18 16:37 UTC, dylanhmorris commented
> Although I am realizing now that I set up the github branch protections to require status checks to pass, which includes deploy of pkgdown but I think deploy wouldn't happen until the PR gets merged to main so maybe I should remove that one

Correct you should require a successful `build` but not a successful `deploy`)

2024-07-18 17:26 UTC, kaitejohnson commented
> > Although I am realizing now that I set up the github branch protections to require status checks to pass, which includes deploy of pkgdown but I think deploy wouldn't happen until the PR gets merged to main so maybe I should remove that one
> 
> Correct you should require a successful `build` but not a successful `deploy`

@dylanhmorris  Would you mind taking a look at this and the ruleset? I tried to specify just `pkgdown / build (pull_request)` in the require status checks before passing but for some reason it still says expected, status waiting to be reported despite the successful build above

2024-07-19 21:07 UTC, dylanhmorris requested changes
Looks largely good, but there are a couple typos that will cause bugs and therefore need to be fixed.

2024-07-19 21:41 UTC, kaitejohnson commented on R/wwinference.R
> +    include_ww = as.numeric(model_spec$include_ww),
It starts as a boolean, but it needs to be coerced to a 0 or 1 to get passed to stan.

2024-07-22 20:47 UTC, dylanhmorris requested changes
a few more tidyeval things, otherwise good.

2024-07-22 20:47 UTC, dylanhmorris commented on R/figures.R
>      draw %in% sampled_draws
```suggestion
    draw %in% !!sampled_draws
```

2024-07-22 20:47 UTC, dylanhmorris commented on R/figures.R
> +      draw %in% sampled_draws
```suggestion
      draw %in% !!sampled_draws
```

2024-07-22 20:47 UTC, dylanhmorris commented on R/figures.R
>      draw %in% sampled_draws
```suggestion
    draw %in% !!sampled_draws
```

2024-07-22 20:47 UTC, dylanhmorris commented on R/figures.R
>      draw %in% sampled_draws
```suggestion
    draw %in% !!sampled_draws
```

2024-07-22 20:48 UTC, dylanhmorris commented on R/figures.R
> +  sampled_draws <- sample(1:max(draws_df$draw), n_draws_to_plot)
^ Can be a separate PR but this should happen @kaitejohnson

2024-07-22 20:51 UTC, dylanhmorris approved these changes
LGTM

2024-07-22 23:41 UTC, merged